name: Run Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Tests
        steps:
            -   uses: actions/checkout@v2
            -   name: Steup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.2
            -   name: Install dependencies
                run: composer install --prefer-dist --no-interaction
            -   name: Run tests
                run: vendor/bin/phpunit
